server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: financial
  profiles:
    active: ${PROFILE}
  
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/financial_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8}
    username: ${DB_USERNAME:financial_user}
    password: ${DB_PASSWORD:financial_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  baseline-version: 0
  validate-on-migrate: true
  clean-disabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  packages-to-scan: com.financial

logging:
  level:
    com.financial: INFO
    org.springframework.web: INFO
    org.flywaydb: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: mySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLongForHS256Algorithm
  expiration: 86400000  # 24 hours in milliseconds
